# medical_insights_dwh/dbt_project/dbt_project.yml
name: 'dbt_project'
version: '1.0.0'
config-version: 2
profile: 'medical_insights' # <--- THIS LINE IS CRUCIAL AND MUST BE PRESENT

# Rest of your dbt_project.yml content follows below...
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to clean when `dbt clean` is run
  - "target"
  - "dbt_packages"

# ... (rest of the file, including your vars section) ...
vars:
  yolo_detections_csv_path: 'D:/10academy/week7/kara_solutions_ethiopian_medical_insights/data/processed/yolo_detections.csv' # <-- This is what I need to see