name: 'medical_insights_dwh' # This should match the name of your dbt project folder
version: '1.0.0'
config-version: 2

profile: 'medical_insights_dwh' # This must match the profile name in ~/.dbt/profiles.yml

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "dbt_modules"

models:
  medical_insights_dwh: # This is your project name again
    staging:
      +materialized: view # Staging models are usually views
      +schema: raw # Create models in a 'raw' schema for staging
    marts:
      +materialized: table # Marts are often tables for performance
      +schema: public # Or your analytical schema like 'analytics'